### PR TITLE
stream: Fix default data won't be received issue

### LINKED ISSUE #169: Empty Proto Hangs Server Streaming RPC
# Description of problem

If a client makes a request to a server streaming RPC (eg: `rpc DivideStream(Sum) returns (stream Part);`) using a default request (eg: `streaming::Sum { ..Default::default() }`), the call hangs indefinitely. This can easily be observed by modifying the [async-stream-client example](https://github.com/containerd/ttrpc-rust/blob/master/example/async-stream-client.rs#L112) to send an empty `Sum`

The root cause is twofold:
1. Empty / Default proto messages serialize to an empty vector
2. The [server implementation](https://github.com/containerd/ttrpc-rust/blob/master/src/asynchronous/server.rs#L605) does not attempt to deliver an empty payload (I think because it assumes it will be receiving DATA messages soon, but the client sends only the request).

# Expected result

The server processes the request and returns the stream to the client.

# Actual result

The server does not execute the corresponding method. The client waits indefinitely for a response.

### LINKED ISSUE #207: Connection lost when sending i32 with value 0 in stream ttrpc
# Description of problem

If we set proto like this in stream (take the example from : https://github.com/containerd/ttrpc-rust/blob/master/example/protocols/protos/streaming.proto)
```
rpc DivideStream(Sum) returns (stream Part);
```
If the `Sum` here contains i32 like
```
message Sum {
	int32 sum = 1;
	int32 num = 2;
}
```
and that **all** i32 values (sum and num) are 0.
⚠️To reproduce the problem, all i32 must be 0, if only sum is 0 or num is 0, then the connection will not lost

In the above case, the connection must be lost. The client side won't return any error and the server side won't receive anything.

This is pretty easy to reproduce, you can change https://github.com/containerd/ttrpc-rust/blob/555c412130e06d9c5632927e7bb7a1a4ed1ca774/example/async-stream-client.rs#L124-L125 sum and num value to 0, and then run the example, then you could find out that server side could not receiver the message

# Expected result

server side receive the message

# Actual result

The client side won't return any error and the server side won't receive anything.

### PR DESCRIPTION
**Pull request by Tim-Zhang**
Protobuf encodes default values, e.g., 0 for number, "" for string, as empty payload and we wouldn't send empty payload to a receiver.

This commit change the method of empty message detecting.

Fixes #169
Fixes #207

### CODE REVIEW

**Comment by jsturtevant** [comment]
would it be worth adding a message to the example that validates this?  Sounds like it is pretty easy to replicate by passing 0's here https://github.com/containerd/ttrpc-rust/blob/555c412130e06d9c5632927e7bb7a1a4ed1ca774/example/async-stream-client.rs#L124-L125?

**Comment by Tim-Zhang** [comment]
@jsturtevant Good suggestion, I've just finished it and please help to review it again, thanks

File: src/asynchronous/client.rs [hunk 1]
```diff
@@ -117,13 +117,20 @@ impl Client {
         streaming_server: bool,
     ) -> Result<StreamInner> {
         let stream_id = self.next_stream_id.fetch_add(2, Ordering::Relaxed);
+        let is_req_payload_empty = req.payload.is_empty();
```
Comment (jsturtevant) [inline src/asynchronous/client.rs:120]: nit: This looks like it is only used when `stream_client` is enabled.  Could move to the line 127?

File: src/asynchronous/server.rs [hunk 2]
```diff
@@ -606,8 +606,8 @@ impl HandlerContext {
         let stream_tx = tx.clone();
         self.streams.lock().unwrap().insert(stream_id, tx);
 
-        let _remote_close = (req_msg.header.flags & FLAG_REMOTE_CLOSED) == FLAG_REMOTE_CLOSED;
-        let _remote_open = (req_msg.header.flags & FLAG_REMOTE_OPEN) == FLAG_REMOTE_OPEN;
```
Comment (jsturtevant) [inline src/asynchronous/server.rs:610]: interesting these don't look like they were used at all 🤷

**Review by jsturtevant — COMMENTED** [review]
LGTM

**Review by wllenyj — APPROVED** [review]
Thanks, LGTM

File: example/async-stream-client.rs [hunk 3]
```diff
@@ -120,12 +120,17 @@ async fn sum_stream(cli: streaming_ttrpc::StreamingClient) {
 
 #[cfg(unix)]
 async fn divide_stream(cli: streaming_ttrpc::StreamingClient) {
+    let mut stream = cli
```
Comment (studychao) [inline example/async-stream-client.rs:123]: nit: Could we create a test case to test the default value specifically instead of messing it into `divide_stream`?

**Review by studychao — COMMENTED** [review]
LGTM but only one small nit

File: src/asynchronous/client.rs (hunk 1 above)
Comment (Tim-Zhang) [reply src/asynchronous/client.rs:120]: unfortunately the compiler says: 
```
error[E0382]: borrow of moved value: `req`
   --> src/asynchronous/client.rs:126:17
    |
115 |         req: Request,
    |         --- move occurs because `req` has type `ttrpc::Request`, which does not implement the `Copy` trait
...
121 |         let mut msg: GenMessage = Message::new_request(stream_id, req)?
    |                                                                   --- value moved here
...
126 |             if !req.payload.is_empty() {
    |                 ^^^^^^^^^^^^^^^^^^^^^^ value borrowed here after move
```

File: example/async-stream-client.rs (hunk 3 above)
Comment (Tim-Zhang) [reply example/async-stream-client.rs]: A new case was added instead of modify one of the exists.

**Review by studychao — APPROVED** [review]

**Review by jsturtevant — APPROVED** [review]
